## configs for neoantigen discovery pipeline

# working directory
WORKDIR: "/data/bases/fangzq/ImmunoRep/data/MSV000082648"

# Input Data
FEATURES: ""
SPECTRUM: ""
SPECTRUM_LOCATION_DICT: ""

PROTEOME_PLUS_CONTAMINATION: "/data/bases/fangzq/ImmunoRep/data/human.proteome.plus.contams.fasta"

# knapsack file 
KNAPSACK: "/data/bases/fangzq/ImmunoRep/neoepitope/ABRF_DDA/fix_C_var_NMQ_knapsack.npy"

# path to neoepitope repo
SMKPATH: "/home/fangzq/github/neoepitope"


dbsearch:
  protein_database: "/data/bases/fangzq/ImmunoRep/data/PA_ucsc_proteome.fasta"
  contaminant: "/data/bases/fangzq/ImmunoRep/data/UniProtContams_259_20170206.fasta"

preprocess:
  train_valid_test_ratio: ""

train:
  epoch: 20
  learning_rate: 0.001
  batch_size: 20


prioritize: ""