# slurm_config.yaml - cluster configuration
__default__:
    partition: normal
    time_min: "02:00:00" # time limit for each job
    cpus: 1
    mem_mb: 4g
    #ntasks-per-node: 14 #Request n cores be allocated per node.
    # output: a_name_for_my_job-%j.out
    # error: a_name_for_my_job-%j.err

train:
    partition: gpu
    cpus: 8
    cpu_mem: 8g
    gpus: 1
    gpus_mem: 16g

test:
    partition: gpu
    cpus: 8
    cpu_mem: 8g
    gpus: 1
    gpus_mem: 16g